import * as dotenv from 'dotenv';
dotenv.config();
const innerHost = process.env.HOST || 'localhost';
const strPort = process.env.PORT || '1337';
const innerPort = parseInt(strPort, 10);
console.log(innerHost);
console.log(innerPort);
export default { host: innerHost, port: innerPort };
export const config = { host: innerHost, port: innerPort };
export const host = innerHost;
export const port = innerPort;
