name: Node.js CI

on: 
  push:
    branches: master
  pull_request:

env:
  NODE_VERSION: ">=14.16.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true